<a href="https://www.kaggle.com/code/theanjalirai/logistic-regression-for-obesity-classification?scriptVersionId=195631038" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Logistic Regression for Obesity Classification

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/kaggle/input/obesity-classification-dataset/Obesity Classification.csv")

In [3]:
df.head()

ID  Age  Gender  Height  Weight   BMI          Label
0   1   25    Male     175      80  25.3  Normal Weight
1   2   30  Female     160      60  22.5  Normal Weight
2   3   35    Male     180      90  27.3     Overweight
3   4   40  Female     150      50  20.0    Underweight
4   5   45    Male     190     100  31.2          Obese

In [4]:
df['Label'].unique()

array(['Normal Weight', 'Overweight', 'Underweight', 'Obese'],
      dtype=object)

In [5]:
df.describe()

ID         Age      Height      Weight         BMI
count  108.000000  108.000000  108.000000  108.000000  108.000000
mean    56.046296   46.555556  166.574074   59.490741   20.549074
std     31.917939   24.720620   27.873615   28.856233    7.583818
min      1.000000   11.000000  120.000000   10.000000    3.900000
25%     28.750000   27.000000  140.000000   35.000000   16.700000
50%     56.500000   42.500000  175.000000   55.000000   21.200000
75%     83.250000   59.250000  190.000000   85.000000   26.100000
max    110.000000  112.000000  210.000000  120.000000   37.200000

In [6]:
df.isnull().sum()

ID        0
Age       0
Gender    0
Height    0
Weight    0
BMI       0
Label     0
dtype: int64

In [7]:
df['Label'].value_counts()

Label
Underweight      47
Normal Weight    29
Overweight       20
Obese            12
Name: count, dtype: int64

In [8]:
df.columns

Index(['ID', 'Age', 'Gender', 'Height', 'Weight', 'BMI', 'Label'], dtype='object')

In [9]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [10]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Gender']])
gender_df = pd.DataFrame(encoded.toarray(),columns = encoder.get_feature_names_out())

In [11]:
df = pd.concat([df,gender_df],axis = 1)

In [12]:
dict = {'Normal Weight' : 1 , 'Underweight' : 0 , 'Overweight' : 2 ,'Obese': 3}

In [13]:
df['Label_encoded'] = df['Label'].map(dict)

In [14]:
df = df.drop("Gender" , axis = 1)
df = df.drop('Label' , axis = 1)

In [15]:
X = df.iloc[:,:-1]
y = df['Label_encoded']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size = 0.20,random_state = 42)

In [17]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs')
model.fit(X_train,y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix , accuracy_score,classification_report
print(confusion_matrix(y_pred , y_test ))
print(accuracy_score(y_pred , y_test ))
print(classification_report(y_pred , y_test ))

[[8 0 0 0]
 [0 4 1 0]
 [0 1 3 1]
 [0 1 0 3]]
0.8181818181818182
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.67      0.80      0.73         5
           2       0.75      0.60      0.67         5
           3       0.75      0.75      0.75         4

    accuracy                           0.82        22
   macro avg       0.79      0.79      0.79        22
weighted avg       0.82      0.82      0.82        22



*see you later...*